AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-ses-email-demo 
      Handler: app.lambda_handler
      CodeUri: hello_world/
      MemorySize: 128
      Environment:
        Variables:
          SENDER_EMAIL: "your_verified_sender@example.com"
          RECIPIENT_EMAIL: "your_verified_recipient@example.com"
      Policies:
        - SESCrudPolicy:
            IdentityName: "*"
